// Clear Horizon: After Effects project builder (generated by render.mjs --ae; rebuild instead of editing)
//
// In After Effects: File > Scripts > Run Script File... and choose this file. It builds a
// "Clear Horizon" folder with a 15 s comp (1920x1080, 60 fps) that stacks the 12 layer passes in
// order (stacked, they rebuild the finished frame), the soundtrack and stems from ae/audio/, bar and
// dive/breach markers, and ../clear-horizon.mp4 as a guide layer.
// Each pass comes from the best source present: ae/passes/NN_name.mov (ProRes 4444 with alpha), then
// ae/passes/NN_name/ (PNG sequence), then the light kit in ae/lite/ (H.264 fill + luma track matte).
// The full-quality passes are large, so they are not in the repository: make them with  node render.mjs --ae
(function () {
  var PASSES = [["01_sky","Sky + sun"],["02_clouds","Clouds"],["03_birds","Birds"],["04_sea","Sea (dot field)"],["05_glitter","Sun glitter"],["06_speed","Speed lines"],["07_motes","Wind motes"],["08_wind","Wind ribbons"],["09_under","Underwater"],["10_under-life","Underwater currents, fish, bubbles"],["11_waterline","Waterline"],["12_splash","Splash"]];
  var MARKERS = [[0,"bar 1"],[2.5,"bar 2"],[5,"bar 3"],[6.433347,"DIVE"],[7.5,"bar 4"],[10,"bar 5"],[11.764609,"BREACH"],[12.5,"bar 6"]];
  var STEMS = ["drums", "bass", "music", "fx"];
  var BASE = new File($.fileName).parent;

  function importFile(f, folder, seq) {
    var io = new ImportOptions(f);
    if (seq) { io.sequence = true; io.forceAlphabetical = true; }
    var item = app.project.importFile(io);
    if (folder) item.parentFolder = folder;
    return item;
  }
  function pass(name, folder) {
    var mov = new File(BASE.fsName + "/passes/" + name + ".mov");
    if (mov.exists) return { item: importFile(mov, folder, false) };
    var dir = new Folder(BASE.fsName + "/passes/" + name);
    var files = dir.exists ? dir.getFiles("*.png") : [];
    if (files.length) {
      files.sort(function (a, b) { return a.name < b.name ? -1 : 1; });
      return { item: importFile(files[0], folder, true) };
    }
    var fill = new File(BASE.fsName + "/lite/" + name + "_fill.mp4"), matte = new File(BASE.fsName + "/lite/" + name + "_matte.mp4");
    if (!fill.exists) return null;
    return { item: importFile(fill, folder, false), matte: matte.exists ? importFile(matte, folder, false) : null, lite: true };
  }

  app.beginUndoGroup("Build Clear Horizon");
  try {
    if (!app.project) app.newProject();
    try { app.project.bitsPerChannel = 16; } catch (e1) {}
    var root = app.project.items.addFolder("Clear Horizon");
    var passFolder = app.project.items.addFolder("Passes"); passFolder.parentFolder = root;
    var audioFolder = app.project.items.addFolder("Audio"); audioFolder.parentFolder = root;
    var comp = app.project.items.addComp("Clear Horizon", 1920, 1080, 1, 15, 60);
    comp.parentFolder = root;
    comp.bgColor = [0.471, 0.784, 0.973];
    var missing = [], lite = 0, i, L, f;
    for (i = 0; i < PASSES.length; i++) {           // bottom to top: AE adds each new layer on top
      var src = pass(PASSES[i][0], passFolder);
      if (!src) { missing.push(PASSES[i][0]); continue; }
      var label = PASSES[i][0].substr(0, 2) + " " + PASSES[i][1];
      if (src.item.mainSource.hasAlpha) src.item.mainSource.alphaMode = AlphaMode.STRAIGHT;
      src.item.mainSource.conformFrameRate = 60;
      L = comp.layers.add(src.item);
      L.name = label;
      if (src.lite) lite++;
      if (src.matte) {
        // the matte goes directly above its fill; its brightness becomes the fill's alpha
        var M = comp.layers.add(src.matte);
        M.name = label + " (matte)";
        if (typeof L.setTrackMatte === "function") L.setTrackMatte(M, TrackMatteType.LUMA);
        else L.trackMatteType = TrackMatteType.LUMA;
        M.enabled = false;
      }
    }
    f = new File(BASE.fsName + "/audio/clear-horizon.wav");
    if (f.exists) {
      L = comp.layers.add(importFile(f, audioFolder, false));
      L.name = "Soundtrack";
      for (i = 0; i < 24; i++) L.property("ADBE Marker").setValueAtTime(i * 0.625, new MarkerValue(i % 4 ? "" : "bar " + (i / 4 + 1)));
    }
    for (i = 0; i < STEMS.length; i++) {
      f = new File(BASE.fsName + "/audio/stems/clear-horizon-" + STEMS[i] + ".wav");
      if (f.exists) importFile(f, audioFolder, false);
    }
    f = new File(BASE.parent.fsName + "/clear-horizon.mp4");
    if (f.exists) {
      L = comp.layers.add(importFile(f, root, false));
      L.name = "Reference render (guide)";
      L.guideLayer = true; L.enabled = false; if (L.hasAudio) L.audioEnabled = false;
    }
    for (i = 0; i < MARKERS.length; i++) comp.markerProperty.setValueAtTime(MARKERS[i][0], new MarkerValue(MARKERS[i][1]));
    comp.openInViewer();
    if (missing.length) alert("Clear Horizon: " + missing.length + " passes were not found.\nMake them with:  node render.mjs --ae");
    else if (lite) alert("Clear Horizon: built from the light kit (H.264 fill + luma matte).\nFor full-quality ProRes 4444 passes run  node render.mjs --ae  and build again.");
  } catch (err) {
    alert("Clear Horizon: the build stopped at line " + err.line + "\n" + err.toString());
  }
  app.endUndoGroup();
})();
